<form action="<?php echo $this->url(array('controller'=>'acervos', 'action'=>'save'),'default',true); ?>" method="POST">
<fieldset class="form-edit">
	<input type="hidden" name="acv_id" id="acv_id" value="<?php echo $this->acervo['acv_id']; ?>">
	
	<ul>
		<li>
			<label for="acv_id_pai">Acervo Pai</label>
			<select name="acv_id_pai" id="acv_id_pai">
				<option value="">Nenhum</option>
				<?php foreach($this->acervos as $acervo) { 
					$select = ($this->acervo['acv_id_pai'] == $acervo->acv_id) ? " selected" : "";
					if ($this->acervo['acv_id'] == $acervo->acv_id) { continue; }
				?>
					<option value="<?php echo $acervo->acv_id; ?>" <?php echo $select; ?>><?php echo $acervo->acv_cota; ?></option>
				<?php } ?>
			<select>
		</li>
		<li>
			<label for="acv_nome">Nome</label>
			<input type="text" name="acv_nome" id="acv_nome" value="<?php echo $this->acervo['acv_nome']; ?>" size="50" required>
		</li>
		<li>
			<label for="acv_cota">Cota</label>
			<input type="text" name="acv_cota" id="acv_cota" value="<?php echo $this->acervo['acv_cota']; ?>" size="50" required>
		</li>
		<li>
			<label for="acv_descricao">Descrição</label>
			<textarea name="acv_descricao" id="acv_descricao" rows="4" cols="80"><?php echo $this->acervo['acv_descricao']; ?></textarea>
		</li>
		<li>
			<label for="acv_tipo_acervo">Tipo</label>
			<select name="acv_tipo_acervo" id="acv_tipo_acervo" required>
				<option></option>
				<option value="1" <?php if($this->acervo['acv_tipo_acervo'] == 1) { echo "selected"; } ?>>Instituição custodiadora</option>
				<option value="2" <?php if($this->acervo['acv_tipo_acervo'] == 2) { echo "selected"; } ?>>Fundo ou Coleção</option>
				<option value="3" <?php if($this->acervo['acv_tipo_acervo'] == 3) { echo "selected"; } ?>>Série</option>
				<option value="4" <?php if($this->acervo['acv_tipo_acervo'] == 4) { echo "selected"; } ?>>Processo ou Dossiê</option>
				<option value="5" <?php if($this->acervo['acv_tipo_acervo'] == 5) { echo "selected"; } ?>>Item Documental</option>
			<select>
		</li>
		<li class="botoes">
			<input type="submit" class="btn" value="Salvar"/>
			<input type="button" class="btn" value="Fechar" onClick="$.featherlight.close();" />
		</li>
	</ul>
</fieldset>
</form>
