<?php
$tipos = array(
	'1' => 'Texto',
	'2' => 'Data',
	'3' => 'Valor numérico',
	'4' => 'Opção'
);
?>


<div class="div-botoes">
	<a class="btn" href="<?php echo $this->url(array('controller'=>'tipos-atributo', 'action'=>'edit'),'default',true) ?>" lightbox="true">
		<img src="/img/icons/set1/plus_16.png"> Novo
	</a>
</div>

<table class="tabela-busca">
	<thead>
		<tr>
			<th width="10%" data-sort="int">Id</th>
			<th width="20%" data-sort="string">Nome</th>
			<th width="20%" data-sort="string">Tipo</th>
			<th width="43%">Descrição</th>
			<th width="7%"></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->tipos as $tipo) { ?>
		<tr>
			<td><?php echo $tipo->ttr_id; ?></td>
			<td><?php echo $tipo->ttr_nome; ?></td>
			<td><?php echo $tipos[$tipo->ttr_tipo]; ?></td>
			<td><?php echo $tipo->ttr_descricao; ?></td>
			<td class="actions">
				<?php if($tipo->ttr_tipo == 4) { ?> <a href="<?php echo $this->url(array('controller'=>'tipos-atributo', 'action'=>'opcoes', 'id'=>$tipo->ttr_id),'default',true) ?>" lightbox="true"><img src="/img/icons/set1/address_16.png"></a> <?php } ?>
				<a href="<?php echo $this->url(array('controller'=>'tipos-atributo', 'action'=>'edit', 'id'=>$tipo->ttr_id),'default',true) ?>" lightbox="true"><img src="/img/icons/set1/document_pencil_16.png"></a>
				<a href="<?php echo $this->url(array('controller'=>'tipos-atributo', 'action'=>'delete', 'id'=>$tipo->ttr_id),'default',true) ?>" delete="true"><img src="/img/icons/set1/delete_16.png"></a>
			</td>
		</tr>
		<?php } ?>
	</tbody>
</table>