<form action="" method="POST">
<fieldset class="form-edit">
	<h2>Log-in</h2>
	<p>Por favor, insira seu nome de usuário e senha para entrar no sistema.</p>
	<ul>
		<li>
			<label for="usu_login">Usuário</label>
			<input type="text" name="usu_login" id="usu_login" size="20">
		</li>
		<li>
			<label for="usu_senha">Senha</label>
			<input type="password" name="usu_senha" id="usu_senha" size="20">
		</li>
		<li class="botoes">
			<input type="submit" class="btn" value="Login"/>
		</li>
		<li><br/>
			<a href="#">Esqueci minha senha.</a>
		</li>
		<li>
			<a href="#">Não tem usuário.</a>
		</li>
	</ul>
</fieldset>
</form>
