<form  action="<?php echo $this->url(array('controller'=>'usuarios', 'action'=>'save-group'),'default',true); ?>" method="POST">
    <fieldset class="form-edit">
        <legend>Grupos do usuário - <?php print_r($this->usuario['nome']); ?></legend>
            <div class="form-group">
                <div class="row" >
                    <div class="col-xs-6">
                        <table>
                            <thead>
                                <td>Grupo<td>
                                <td>Papel<td>
                            </thead>
                            <?php
                                if(!empty($this->usuario['dados'])){
                                    foreach($this->usuario['grupo'] as $grupo) {
                                        foreach ($this->usuario['dados'] as $dados) {
                                            if ($dados->gtr_id == $grupo->gtr_id) {
                                                echo "<tr><td><input type='checkbox' name='gtr_nome' id='$grupo->gtr_id' value='$grupo->gtr_nome'checked>" . $grupo->gtr_nome . "<td/>";
                                                if ($dados->aug_papel == 1) {
                                                    echo "<td><select name='aug_papel' id='$grupo->gtr_id' >
                                                        <option value='1' selected>Líder</option>
                                                        <option value='2'>Monitor</option>
                                                        <option value='3'>Operador</option>
                                                        </select></td></tr>";
                                                } else if ($dados->aug_papel == 2) {
                                                    echo "<td><select name='aug_papel' id='$grupo->gtr_id'>
                                                        <option value='1'>Líder</option>
                                                        <option value='2'selected>Monitor</option>
                                                        <option value='3'>Operador</option>
                                                        </select></td></tr>";
                                                } else if ($dados->aug_papel == 3) {
                                                    echo "<td><select name='aug_papel' id='$grupo->gtr_id' >
                                                        <option value='1'>Líder</option>
                                                        <option value='2'>Monitor</option>
                                                        <option value='3'selected>Operador</option>
                                                        </select></td></tr>";
                                                }
                                            }else{
                                                echo "<tr><td><input type='checkbox' name='gtr_nome' id='$grupo->gtr_id' value='$grupo->gtr_nome'>".$grupo->gtr_nome."<td/>";
                                                echo "<td><select name='aug_papel' id='$grupo->gtr_id' disabled>
                                                        <option value='lider'>Líder</option>
                                                        <option value='monitor'>Monitor</option>
                                                        <option value='operador'>Operador</option>
                                                        </select></td></tr>";

                                            }
                                        }
                                    }
                                }else{
                                    foreach($this->usuario['grupo'] as $grupo) {
                                        echo "<tr><td><input type='checkbox' name='gtr_nome' id='$grupo->gtr_id' value='$grupo->gtr_nome'>" . $grupo->gtr_nome . "<td/>";
                                        echo "<td><select name='aug_papel' id='$grupo->gtr_id' disabled>
                                            <option value='lider'>Líder</option>
                                            <option value='monitor'>Monitor</option>
                                            <option value='operador'>Operador</option>
                                            </select></td></tr>";
                                    }
                                }
                                 ?>
                        </table>
                    </div>
                </div>
                <input type="submit" class="btn" value="Salvar"/>
                <input type="button" class="btn" value="Voltar" onClick='$.featherlight.close();' />
            </div>
    </fieldset>
</form>

<script type="text/javascript">
    $(document).on('change', '.checkbox', function() {
        if(this.checked) {
            // checkbox is checked
            console.log("change");
        }
    });
</script>