<div class="div-botoes">
	<a class="btn" href="<?php echo $this->url(array('controller'=>'predefinitions', 'action'=>'edit'),'default',true) ?>" lightbox="true">
		<img src="/img/icons/set1/plus_16.png"> Novo
	</a>
</div>

<table class="tabela-busca">
	<thead>
		<tr>
			<th width="4%" data-sort="int">Id</th>
			<th width="25%" data-sort="string">Nome</th>
			<th width="40%">Descrição</th>
			<th width="25%">Arquivo</th>
			<th width="6%"></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->predefinitions as $predefinition) { ?>
		<tr>
			<td><?php echo $predefinition->pre_id; ?></td>
			<td><?php echo $predefinition->pre_name; ?></td>
			<td><?php echo $predefinition->pre_description; ?></td>
			<td><?php echo $predefinition->pre_file; ?></td>
			<td class="actions">
				<a href="<?php echo $this->url(array('controller'=>'predefinitions', 'action'=>'edit', 'id'=>$predefinition->pre_id),'default',true) ?>" lightbox="true"><img src="/img/icons/set1/document_pencil_16.png"></a>
				<a href="<?php echo $this->url(array('controller'=>'predefinitions', 'action'=>'delete', 'id'=>$predefinition->pre_id),'default',true) ?>" delete="true"><img src="/img/icons/set1/delete_16.png"></a>
			</td>
		</tr>
		<?php } ?>
	</tbody>
</table>